server:
  port: ${PORT:${SERVER_PORT:9000}}
spring:
  profiles:
    active: development
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.neo4j.*: INFO
    org.apache.kafka.*: WARN
    liquibase.integration.spring.SpringLiquibase: ERROR
---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: 'update'
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc.lob.non_contextual_creation: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
eventapis:
  baseEventsPackage: com.example.orderservice.event
  storeConfig:
    contactPoints: ${CASSANDRA_HOST:localhost}:${CASSANDRA_PORT:9042}
    keyspaceName: eventapis
    username: cassandra
    password: cassandra
  eventRecords:
    order: orderevents
  eventBus:
    bootstrapServers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      groupId: order-service-group